using System.Data;
using System.Web;

public class ArquivoConciliacaoDAO
{
    private Conexao _conn;

	public ArquivoConciliacaoDAO(Conexao c)
	{
        _conn = c;
	}

	public DataTable ArquivoConciliacao(string De, string Ate)
    {
		string sql = @"

		SELECT
				  LC.COD_EMPRESA AS CÓDIGO_EMPRESA,
				  REPLACE(REPLACE(REPLACE(EMP.NOME_RAZAO_SOCIAL, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS RAZÃO_SOCIAL,
				  LC.LOTE AS NÚMERO_LOTE,
				  FORMAT(LC.DATA, 'dd/MM/yyyy') AS DATA,
				  REPLACE(REPLACE(REPLACE(LC.COD_CONTA, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS CÓDIGO_CONTA,
				  REPLACE(REPLACE(REPLACE(CC.DESCRICAO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS DESCRIÇÃO_CONTA,
				  LC.COD_JOB AS CÓDIGO_JOB,
				  REPLACE(REPLACE(REPLACE(CJ.DESCRICAO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS DESCRIÇÃO_JOB,
				  CJ.COD_DIVISAO AS CÓDIGO_DIVISÃO,
				  REPLACE(REPLACE(REPLACE(CD.DESCRICAO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS DESCRIÇÃO_DIVISÃO,
				  CJ.COD_LINHA_NEGOCIO AS CÓDIGO_LINHA_NEGÓCIO,
				  REPLACE(REPLACE(REPLACE(CLN.DESCRICAO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS DESCRIÇÃO_LINHA_NEGÓCIO,
				  LC.COD_CLIENTE AS CÓDIGO_CLIENTE,
				  REPLACE(REPLACE(REPLACE(CE.NOME_RAZAO_SOCIAL, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS NOME_CLIENTE,
				  SUM(LC.QTD) AS QUANTIDADE,
				  SUM(LC.VALOR) AS VALOR,
				  LC.DEB_CRED AS DÉBITO_CRÉDITO,
				  REPLACE(REPLACE(REPLACE(LC.HISTORICO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS HISTÓRICO,
				  LC.COD_TERCEIRO AS CÓDIGO_TERCEIRO,
				  REPLACE(REPLACE(REPLACE(ISNULL(CT.NOME_RAZAO_SOCIAL, ''), CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS NOME_TERCEIRO,
				  REPLACE(REPLACE(REPLACE(LC.TIPO_LANCTO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS TIPO_LANÇAMENTO,
				  REPLACE(REPLACE(REPLACE(ISNULL(CU.NOME_COMPLETO, ''), CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS USUÁRIO,
				  REPLACE(REPLACE(REPLACE(LC.NUMERO_DOCUMENTO, CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), '') AS NÚMERO_DOCUMENTO

		FROM
				  LANCTOS_CONTAB LC
				  LEFT JOIN CAD_EMPRESAS CT ON CT.COD_EMPRESA = LC.COD_TERCEIRO
				  LEFT JOIN CAD_USUARIOS CU ON LC.COD_USUARIO = CU.COD_USUARIO,
				  CAD_JOBS CJ,
				  CAD_EMPRESAS CE,
				  CAD_CONTAS CC,
				  CAD_LINHA_NEGOCIOS CLN,
				  CAD_DIVISOES CD,
				  CAD_EMPRESAS EMP

		WHERE
					  LC.COD_EMPRESA = " + HttpContext.Current.Session["empresa"] + @"
				  AND LC.COD_JOB = CJ.COD_JOB
				  AND CJ.COD_DIVISAO = CD.COD_DIVISAO
				  AND CJ.COD_LINHA_NEGOCIO = CLN.COD_LINHA_NEGOCIO
				  AND LC.COD_CONTA = CC.COD_CONTA
				  AND LC.COD_EMPRESA = CC.COD_EMPRESA
				  AND LC.COD_CLIENTE = CE.COD_EMPRESA
				  AND LC.PENDENTE = 'FALSE'
				  AND LC.COD_EMPRESA = EMP.COD_EMPRESA
				  AND LC.DATA BETWEEN '" + De + "' AND '" + Ate + @"'

		GROUP BY
				  LC.COD_EMPRESA,
				  EMP.NOME_RAZAO_SOCIAL,
				  LC.LOTE,
				  LC.DATA,
				  LC.COD_CONTA,
				  CC.DESCRICAO,
				  LC.COD_JOB,
				  CJ.DESCRICAO,
				  CJ.COD_DIVISAO,
				  CD.DESCRICAO,
				  CJ.COD_LINHA_NEGOCIO,
				  CLN.DESCRICAO,
				  LC.COD_CLIENTE,
				  CE.NOME_RAZAO_SOCIAL,
				  LC.DEB_CRED,
				  LC.HISTORICO,
				  LC.COD_TERCEIRO,
				  REPLACE(REPLACE(REPLACE(ISNULL(CT.NOME_RAZAO_SOCIAL, ''), CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), ''),
				  LC.TIPO_LANCTO,
				  REPLACE(REPLACE(REPLACE(ISNULL(CU.NOME_COMPLETO, ''), CHAR(13) + CHAR(10), ''), CHAR(13), ''), CHAR(10), ''),
				  LC.NUMERO_DOCUMENTO

		ORDER  BY
				  LC.COD_EMPRESA,
				  EMP.NOME_RAZAO_SOCIAL,
				  LC.DATA";

		return _conn.dataTable(sql, "dtArquivoConciliacao");
    }
}